//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject1A
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENDER
    {
        public int ID { get; set; }
        public string First_Name { get; set; }
        public string Mid_Name { get; set; }
        public string Last_Name { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
        public string Gender1 { get; set; }
        public string Address { get; set; }
        public string Previous_School { get; set; }
        public string Birth_Entry_Number { get; set; }
        public string Grade { get; set; }
        public string Class { get; set; }
    }
}
