//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject1A
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public int ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Contact_Number { get; set; }
        public Nullable<int> Student_ID { get; set; }
        public string Relationship { get; set; }
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
    
        public virtual Student_detail Student_detail { get; set; }
    }
}
