//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject1A
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Choice_Christian_AcademyEntities : DbContext
    {
        public Choice_Christian_AcademyEntities()
            : base("name=Choice_Christian_AcademyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emergency_contact> Emergency_contact { get; set; }
        public virtual DbSet<House> Houses { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Student_Detail> Student_Detail { get; set; }
        public virtual DbSet<Subject_Table> Subject_Table { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Test_Result> Test_Result { get; set; }
    }
}
