//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject1A
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Detail
    {
        public int ID { get; set; }
        public int Student_ID { get; set; }
        public int Teacher_ID { get; set; }
        public int House_ID { get; set; }
        public int Parent_ID { get; set; }
        public Nullable<int> Test_Result_ID { get; set; }
    
        public virtual House House { get; set; }
        public virtual Parent Parent { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
