//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject1A
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student_detail()
        {
            this.Parents = new HashSet<Parent>();
            this.Registrations = new HashSet<Registration>();
            this.Test_Result1 = new HashSet<Test_Result>();
        }
    
        public int Student_ID { get; set; }
        public string First_Name { get; set; }
        public string Mid_Name { get; set; }
        public string Last_Name { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
        public string Gender { get; set; }
        public string Height_ft { get; set; }
        public string Height_in { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone_Num { get; set; }
        public string Previous_School { get; set; }
        public string Birth_Entry_Number { get; set; }
        public string AddInfo { get; set; }
        public Nullable<int> House_ID { get; set; }
        public Nullable<int> Grade_ID { get; set; }
        public Nullable<int> Class_ID { get; set; }
        public Nullable<int> Teacher_ID { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public Nullable<int> Test_Result_ID { get; set; }
        public Nullable<int> Image_ID { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual House House { get; set; }
        public virtual Image Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parent> Parents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration> Registrations { get; set; }
        public virtual Test_Result Test_Result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test_Result> Test_Result1 { get; set; }
    }
}
